language: c++

cache:
  directories:
    - download

matrix:
  include:

    # macOS
    - os: osx
      sudo: required
      env:
        - _BUILD=macos
      install:
        - brew install libsamplerate
        - brew install libsndfile
      script:
        - bash .travis/script-macos.sh
        - cp -av bin ninjas2-"$_BUILD"
        - rm -f ninjas2-"$_BUILD"/README
        - install -d release
        - zip -9 -r release/ninjas2-"$_BUILD".zip ninjas2-"$_BUILD"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: release/*
  file_glob: true
  skip_cleanup: true
  prerelease: true
  #draft: true
  overwrite: true
  on:
    branch: master

# TODO: replace me $GITHUB_TOKEN (a personal access token with repo rights)
#  travis login --com
#  travis encrypt GITHUB_TOKEN=<the-token-value> --com --add
env:
  global:
    secure: KQIx0K9HNyKwGW793K6LzGIY38E9Ax2JLyzzu62T/u1JGQYSZ0z4V4suVzMcDAPbq1dsmn6ni4jEWPJyC7jgwwAdU52tv7YqYIXAf1ZbnbPL3Tykuh3DPNKwGVlimZzd4gl7C+Qg+gMYdu0mVYceB0i+T6F+U/O23sTwDsX7rtpegEj56jRPc5+VCjpNTDnGifHvtNaXgnPMx6Gf9nW/IsXNCGfdnQSPLPGHnNLmNLJvIJX3AbXgTgE66vT8+8ZcGcTg3W5YKOp6qnEUb3fo8qFdrG39yKBdf4qguy2zSAktPVozn7GshyCmo6GtLbPcti+nLN/BfcqJvazb3NWJ2ivevg/FnNxQtu8/UCB4gLIS+LRsvndhGT/FcpnW/WhOolgmQJnwFPU/0sRY63/gixWWN3/wzX/2mwwbkFWbJ6nYW0sO7YR4YCrEwzxAVF8ZzoWVvZFFLt2vkEGK1/rnWGca3+Xx3LPudnIa3dbvlVhJWYzLpWshHa+YdZtB0G34t2azquMIQVbll1EpgiuE0slZ1SIKnMqGftLxsDPq2gAc1Zu7g9mx4IzsHBoDaVI5ENr+X6iT6KMLEJWJJJbrn+zTSHu0L+ITjdkr2YA6IXYVQoie7lcjh2j7iMs4Jsc/RO+nbBtegUImAfrmD3bsku/BXGpZYKmeg2F6+eCJM+Q=
